apiVersion: v1
kind: Pod
metadata:
  name: test-volume
spec:
  restartPolicy: Never
  volumes:
  - name: shares
    emptyDir: {}
  containers:
  - name: test-nginx
    image: nginx
    volumeMounts:
    - name: shares
      mountPath: /user/share/nginx/html
  - name: test-debian
    image: debian
    volumeMounts:
    - name: shares
      mountPath: /test-volume
    command: ["/bin/sh"]
    args: ["-c", "echo Hello Volume! > /test-volume/index.html"]
